<?php

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * @link https://git.drupalcode.org/project/content_moderation_notifications
 */
function content_change_status_send_mail_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::logger('custom_mail_module')->notice('yahho');
  $mailManager = \Drupal::service('plugin.manager.mail');
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $params['subject'] = 'さぶじぇくと';
  $params['message'] = 'test送信';

  $result = $mailManager->mail(
    'content_change_status_send_mail',
    'content_moderation_notification',
    'p20prosugi@gmail.com',
    $langcode,
    $params
  );
}

/**
 * Implements hook_mail().
 */
function content_change_status_send_mail_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  $message['to'] = 'p20prosugi@gmail.com';
  $message['from'] = \Drupal::config('system.site')->get('mail');
  $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);
  $message['body'][] = $params['message'];
}

