_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: ja
module:
  block: 0
  breakpoint: 0
  config_translation: 0
  content_moderation: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  entity_clone: 0
  entity_clone_extras: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  minimal: 0
  mysql: 0
  node: 0
  node_choice_page_override: 0
  node_language_select_page_add_custom_moderation: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  storage: 0
  system: 0
  text: 0
  toolbar: 0
  twig_tweak: 0
  twig_xdebug: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  content_translation: 10
  views: 10
  paragraphs: 11
theme:
  claro: 0
  stable9: 0
  mytheme: 0
profile: minimal
