cloneable_entities:
  - block
  - field_storage_config
  - field_config
  - file
  - filter_format
  - configurable_language
  - language_content_settings
  - node
  - node_type
  - path_alias
  - menu
  - action
  - user_role
  - user
  - base_field_override
  - entity_form_mode
  - entity_form_display
  - entity_view_display
  - entity_view_mode
  - date_format
  - storage
  - storage_type
  - workflow
  - content_moderation_state
  - image_style
  - media
  - media_type
  - view
  - paragraphs_type
  - paragraph
